### ISSUE TITLE
possible issue?

### ISSUE THREAD

**Issue by CupidonSauce173** [Muqsit/FormImagesFix#1]
Not sure if I am doing anything wrong but the fix doesn't actually work. It still takes ages to load up images and it sends a blank title to the player. Using FormAPI on the lastest pmmp build, do I have to do any modifications on how FormAPI works or ?

**Comment by Muqsit** [comment]
No, you just need to install the phar file from poggit.
API 3: https://poggit.pmmp.io/r/77731/FormImagesFix_dev-8.phar
API 4: https://poggit.pmmp.io/r/77732/FormImagesFix_dev-9.phar

**Comment by Muqsit** [comment]
Do note, if the image URL you're using is hosted on a very slow network, or if the client has a very bad network, the first call will take just as long as before.
Basically, the time taken to send the form and get a confirmation back from the client must be less than the latency between the client and the image URL.
latency between client -> image host < 2x latency between client -> server

**Comment by CupidonSauce173** [comment]
> Do note, if the image URL you're using is hosted on a very slow network, or if the client has a very bad network, the first call will take just as long as before.

Weird, the network has a 1Gbits/s speed of download. Might be the host, I'll try hosting the images on the same machine, thanks

**Comment by Muqsit** [comment]
A method to tackle this issue would be sending the attribute several times (instead of only once) for a good amount of time (i'd say 5 times, once each 10 ticks, so that's taking care of up to 2500ms).
