### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HighestDreams** [Muqsit/FormImagesFix#11]
Screenshot of the error : 

![image](https://user-images.githubusercontent.com/79803040/155610505-e764df83-6b8c-4cf5-8542-cf4f2c043b97.png)

Pocket-mine version : 4.2.0
(I am using Api 4 version of this plugin)

+ When player join to the server, gives this error.

**Comment by Muqsit** [comment]
`FormImagesFix_dev-9.phar` is a 2 year old build, download [`FormImagesFix_dev-14.phar`](https://poggit.pmmp.io/r/146450/FormImagesFix_dev-14.phar) from https://poggit.pmmp.io/ci/Muqsit/FormImagesFix/~

**Comment by HighestDreams** [comment]
Tysm
