### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BlueWhaleYT** [Muqsit/FormImagesFix#2]
`muqsit\formimagesfix\Main::onEnable() must be public (as in class pocketmine\plugin\PluginBase) in phar:///home/container/plugins/FormImagesFix.phar/src/muqsit/formimagesfix/Main.php on line 20`

**Comment by Muqsit** [comment]
You're running the version of this plugin that's targeting API 4 but your server runs on API 3.

See https://github.com/Muqsit/FormImagesFix/issues/1#issuecomment-595685831

Also probably why you should stop using an AllAPILoader. Plugins like that mask the real error.
