### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by Kjenium** [Muqsit/FormImagesFix#3]
Idk why but it used to work on my server.pro server but when I moved to a vps it doesn't work anymore

**Comment by Muqsit** [comment]
See https://github.com/Muqsit/FormImagesFix/issues/1#issuecomment-595686464

**Comment by Kjenium** [comment]
The thing is I used the same url i used on server.pro and now doesn't work. I'm used a wikipedia url and  i'm still using it.I host now on my dedicated server so That would work better but it doesn't work

**Comment by Kjenium** [comment]
so the problem are not urls
If i click another program opened and i go back to minecraft it instantly load.
