### ISSUE TITLE
Update api 4.0.0

### ISSUE THREAD

**Issue by UnEnanoMas** [Muqsit/FormImagesFix#6]
Could not load plugin 'FormImagesFix': Incompatible API version (plugin requires one of: 4.0.0)

**Comment by xerenahmed** [comment]
Download from https://github.com/Muqsit/FormImagesFix/tree/pm-4.0

**Comment by Muqsit** [comment]
![image](https://user-images.githubusercontent.com/15074389/85948680-9cb57b80-b96b-11ea-992d-16291d813be8.png)
Use `master` branch if your on api3
