### ISSUE TITLE
The plugin has stopped working

### ISSUE THREAD

**Issue by UnEnanoMas** [Muqsit/FormImagesFix#8]
Currently: 06/12/2020

For pocketmine version 3.16.0
Minecraft: 1.16.100
Php: 7.3
Dev: # 11

The plugin no longer does the function it had, it no longer loads the images faster

**Comment by Muqsit** [comment]
This plugin relies on hacky methods to get form images to show up. The hack is no longer working as per the new protocol.

**Comment by UnEnanoMas** [comment]
I think it is better to leave this issue open so that you will not have more

**Comment by Huygamess** [comment]
I can't úe plugin elo

**Comment by llPushkarSinghll** [comment]
It works!
